{
 "title": "Orbs PROD DevOps",
 "tags": [
  "orbs",
  "stability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "vchain", "query": "label_values(vchain)" },
   { "name": "validator", "query": "label_values(machine)" }
  ]
 },
 "panels": [
  {
   "title": "Block Height (Max)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(BlockStorage_BlockHeight{vcid=~\"$vchain\"})"
    }
   ]
  },
  {
   "title": "# Live Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (machine) (BlockStorage_BlockHeight{vcid=~\"$vchain\"}))"
    }
   ]
  },
  {
   "title": "#  Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "total_node_count" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 0 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(Runtime_Uptime_Seconds{vcid=~\"$vchain\"})"
    }
   ]
  },
  {
   "title": "Height Lag",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(BlockStorage_BlockHeight{vcid=~\"$vchain\"})-min(BlockStorage_BlockHeight{vcid=~\"$vchain\"})"
    }
   ]
  },
  { "title": "Local time", "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 5, "x": 18, "y": 0 } },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Time since last committed block",
   "type": "table-old",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "targets": [
    { "expr": "Meta_TimeSinceLastBlock_Millis" }
   ]
  },
  {
   "title": "Last Seen",
   "type": "table-old",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "targets": [
    { "expr": "-Meta_TimeSinceLastSeen_Millis" }
   ]
  },
  {
   "title": "Committed TPS per node",
   "type": "graph",
   "description": "Transactions per second in closed blocks",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(TransactionPool_TotalCommits_Count{vcid=~\"$vchain\", machine=\"$validator\"}[1m])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Current Lean Helix Election View",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ConsensusAlgo_LeanHelix_CurrentElection_Number{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Memory usage per node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "OS_Process_Memory_Bytes{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Ethereum Node Last Block",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "Ethereum_Node_LastBlock{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Block Storage size on disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "BlockStorage_FileSystemSize_Bytes{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "BlockStorage_BlockHeight{vcid=~\"$vchain\"}",
     "legendFormat": "Block Storage: {{machine}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Runtime_NumGoroutine_Number{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Latest committed block",
   "type": "table-old",
   "description": "Measured on BlockStorage service",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "BlockStorage_BlockHeight{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "State Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "StateStoragePersistence_TotalNumberOfKeys_Count{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Time since restart",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "Runtime_Uptime_Seconds{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Ethereum Node Last Block",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 19 },
   "targets": [
    { "rawSql": "select * from validators" }
   ]
  },
  {
   "title": "TransactionPool Committed size (bytes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "TransactionPool_CommittedPool_PoolSize_Bytes{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Transaction Pool Committed count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "TransactionPool_CommittedPool_Transactions_Count{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Incoming transactions per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(PublicApi_TotalTransactionsFromClients_Count{vcid=~\"$vchain\"}[1m])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Transactions in Pending Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "TransactionPool_PendingPool_Transactions_Count{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "TransactionPool Pending size (bytes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "TransactionPool_PendingPool_PoolSize_Bytes{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Process CPU 100-p",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(1,OS_Process_CPU_PerCent{vcid=~\"$vchain\"}[1m])  ",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Block Storage disk space increase bytes/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(BlockStorage_FileSystemSize_Bytes{vcid=~\"$vchain\"}[2m])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Blocks closed per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(BlockStorage_BlockHeight{vcid=~\"$vchain\"}[30s])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Ethereum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "BlockHeight diffs between Services within node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "BlockStorage_BlockHeight{vcid=~\"$vchain\"}-TransactionPool_BlockHeight{vcid=~\"$vchain\"}",
     "legendFormat": "BlockStorage - TransactionPool"
    },
    {
     "expr": "BlockStorage_BlockHeight{vcid=~\"$vchain\"}-StateStorage_BlockHeight{vcid=~\"$vchain\"}",
     "legendFormat": "BlockStorage - StateStorage"
    }
   ]
  },
  {
   "title": "Errors adding to Transaction Pool / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(PublicApi_TotalTransactionsErrAddingToTxPool_Count{vcid=~\"$vchain\"}[1m])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Error nil transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "PublicApi_TotalTransactionsErrNilRequest_Count{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Error invalid transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "PublicApi_TotalTransactionsErrInvalidRequest_Count{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Error duplicate transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "PublicApi_TotalTransactionsErrDuplicate_Count{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Block Validation Failures / minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(BlockSync_ProcessingBlocksState_FailedToValidateBlocks_Count{vcid=~\"$vchain\"}[1m])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Keepalive errors  / 10m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Gossip_OutgoingConnection_KeepaliveErrors_Count{vcid=~\"$vchain\"}[10m])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Process CPU 90-p",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.9,OS_Process_CPU_PerCent{vcid=~\"$vchain\"}[1m])  ",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "Runtime_Uptime_Seconds{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Time drift (in seconds)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "OS_Time_Drift_Millis{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "TX Pool Commit Rate tx/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "TransactionPool_CommitRate_PerSecond{vcid=~\"$vchain\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  { "title": "OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } }
 ]
}