{
 "title": "Summary",
 "tags": [
  "orbs",
  "stability"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Block Height (Max)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "max(BlockStorage_BlockHeight) " }
   ]
  },
  {
   "title": "# Live Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (machine) (BlockStorage_BlockHeight))"
    }
   ]
  },
  {
   "title": "#  Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "total_node_count" }
   ]
  },
  {
   "title": "Height Lag",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(BlockStorage_BlockHeight)-min(BlockStorage_BlockHeight)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "expr": "max(Runtime_Uptime_Seconds)" }
   ]
  },
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming transactions per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(PublicApi_TotalTransactionsFromClients_Count[1m])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Committed TPS per node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(TransactionPool_TotalCommits_Count[1m])",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Current Lean Helix Election View",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(ConsensusAlgo_LeanHelix_CurrentElection_Number) by (machine)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "TX Service time median",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "PublicApi_SendTransactionProcessingTime_Millis{aggregation=\"median\"}"
    }
   ]
  },
  {
   "title": "TX Service time 95-percentile",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "PublicApi_SendTransactionProcessingTime_Millis{aggregation=\"95p\"}"
    }
   ]
  },
  {
   "title": "TX Service time 99-percentile",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "PublicApi_SendTransactionProcessingTime_Millis{aggregation=\"99p\"}"
    }
   ]
  },
  {
   "title": "TX Service time max",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "PublicApi_SendTransactionProcessingTime_Millis{aggregation=\"max\"}"
    }
   ]
  },
  {
   "title": "TX Service time samples",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "PublicApi_SendTransactionProcessingTime_Millis{aggregation=\"count\"}"
    }
   ]
  },
  {
   "title": "Memory usage per node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "OS_Process_Memory_Bytes", "legendFormat": "{{machine}}" }
   ]
  },
  {
   "title": "Block Height",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "max_over_time(BlockStorage_BlockHeight[1m])"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "BlockStorage_BlockHeight", "legendFormat": "{{machine}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "Runtime_Uptime_Seconds", "legendFormat": "{{machine}}" }
   ]
  },
  {
   "title": "Transactions in Pending Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "TransactionPool_PendingPool_Transactions_Count",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  { "title": "OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } }
 ]
}